name: "godot-build"
on: push

env:
  GODOT_VERSION: 4.0.3
  EXPORT_NAME: test-project
  ITCHIO_USERNAME: ${{ vars.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ vars.ITCHIO_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows-Desktop, Web]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true          
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: example
          preset: ${{ matrix.platform }}
      - name: Upload Artifact to Itch with Butler
        id: release
        run: | 
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler push ${{ github.workspace }}/${{ steps.build.outputs.build }} $ITCHIO_USERNAME/$ITCHIO_GAME:${{ matrix.platform }}